name: Deploy Python Function with Container

on:
  workflow_dispatch:
  push:
    branches:
    - 'container'

env:
  AZURE_BASE_NAME: 'cdw-functesting-20240411'
  CONTAINER_NAME: 'cwiederspan/cdwfunctesting:latest'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: ./src
        tags: ${{ env.CONTAINER_NAME }}

    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Resources
      uses: azure/cli@v2
      with: 
        inlineScript: |
          cd ./infra
          az deployment group create -g ${{ env.AZURE_BASE_NAME }} --template-file main-container.bicep --parameters baseName='${{ env.AZURE_BASE_NAME }}' imageName='${{ env.CONTAINER_NAME }}' 
