name: Deploy Python Function

on:
  [workflow_dispatch]

env:
  AZURE_BASE_NAME: 'cdw-functesting-20240411'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Setup NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Azure Core Tools
      shell: bash
      run: |
        npm i -g azure-functions-core-tools@4 --unsafe-perm true

    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Resources
      uses: azure/cli@v2
      with: 
        inlineScript: |
          cd ./infra
          az deployment group create -g ${{ env.AZURE_BASE_NAME }} --template-file main.bicep

    - name: Deploy Function
      shell: bash
      run: |
        cd ./src
        func azure functionapp publish ${{ env.AZURE_BASE_NAME }}-app --python
