name: Deploy Python Function

on:
  [workflow_dispatch]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'cdw-functesting-20240409-app'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                    # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Azure Core Tools
      shell: bash
      run: |
        npm i -g azure-functions-core-tools@4 --unsafe-perm true
         
    # - name: Install Azure Core Tools
    #   shell: bash
    #   run: |
    #       curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
    #       sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
    #       sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
    #       sudo apt-get update
    #       sudo apt-get install azure-functions-core-tools-4
    #       func --version

    - name: Deploy Function
      shell: bash
      run: |
        cd ./src
        func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --python
