name: Deploy Python Function

on:
  [workflow_dispatch]

env:
  AZURE_FUNCTIONAPP_NAME: 'cdw-functesting-20240409-app'   # set this to your function app name on Azure

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Azure Core Tools
      shell: bash
      run: |
        npm i -g azure-functions-core-tools@4 --unsafe-perm true

    - name: Deploy Function
      shell: bash
      run: |
        cd ./src
        func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }} --python
