name: Deploy Python Function

on:
  [workflow_dispatch]

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: 'cdw-functesting-20240409-app'   # set this to your function app name on Azure
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'       # set this to the path to your function app project, defaults to the repository root
  PYTHON_VERSION: '3.11'                    # set this to the python version to use (e.g. '3.6', '3.7', '3.8')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
         
    - name: Install Azure Core Tools
      shell: bash
      run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-4

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: 2.59.0
        inlineScript: |
          func azure functionapp publish ${{ env.AZURE_FUNCTIONAPP_NAME }}

    # - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
    #   uses: actions/setup-python@v4
    #   with:
    #     python-version: ${{ env.PYTHON_VERSION }}

    # - name: 'Resolve Project Dependencies Using Pip'
    #   shell: bash
    #   run: |
    #     pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
    #     python -m pip install --upgrade pip
    #     pip install -r requirements.txt --target=".python_packages/lib/site-packages"
    #     popd

    # - name: 'Run Azure Functions Action'
    #   uses: Azure/functions-action@v1
    #   id: fa
    #   with:
    #     app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
    #     package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    #     publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    #     scm-do-build-during-deployment: true
    #     enable-oryx-build: true